# frozen_string_literal: true

module DiscordGameSDK
  VERSION = "0.1.1"
  DISCORD_VERSION = "2"
  DISCORD_APPLICATION_MANAGER_VERSION = "1"
  DISCORD_USER_MANAGER_VERSION = "1"
  DISCORD_IMAGE_MANAGER_VERSION = "1"
  DISCORD_ACTIVITY_MANAGER_VERSION = "1"
  DISCORD_RELATIONSHIP_MANAGER_VERSION = "1"
  DISCORD_LOBBY_MANAGER_VERSION = "1"
  DISCORD_NETWORK_MANAGER_VERSION = "1"
  DISCORD_OVERLAY_MANAGER_VERSION = "1"
  DISCORD_STORAGE_MANAGER_VERSION = "1"
  DISCORD_STORE_MANAGER_VERSION = "1"
  DISCORD_VOICE_MANAGER_VERSION = "1"
  DISCORD_ACHIEVEMENT_MANAGER_VERSION = "1"
end
